const authToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU3ZDdhN2U4YjJjNTRkYmQ1MDJkMTUiLCJlbWFpbCI6ImFsZXhhbmRyZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFsZXhhbmRyZSIsImlhdCI6MTY1MDAwNzMxNiwiZXhwIjoxNjUwMDI4OTE2fQ.1iNyrNfoN4PfdD8vhFGOewcooBc8RxxpJLdEsiZxn6M";

export default authToken;
