const authToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU4MzgxMjk4NTMyZjMzNTZjN2Q5MjAiLCJlbWFpbCI6ImFsZXhhbmRyZUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImFsZXhhbmRyZSIsImlhdCI6MTY1MDI2Nzg2NSwiZXhwIjoxNjUwMjg5NDY1fQ.vEybaXfmqa-2Q_7uEv_oNFGcJJcshcSoOA3zjKdNMt8";

export default authToken;
